### ISSUE TITLE
Regression seen after fix for #13

### ISSUE THREAD

**Issue by msmigiel** [kuthulux/gnome-connection-manager#18]
Operating System: RHEL 7.8
Program Version: GCM 1.2.0

With the fix for issue #13 consumed, I am seeing a new error. If I right click on a server and say Edit, I see the below error:

```
Traceback (most recent call last):
  File "gnome_connection_manager.py", line 1995, in on_bntEdit_clicked
    wHost.init(host.group, host)
  File "gnome_connection_manager.py", line 2455, in init
    self.txtTerm.set_text(host.term)
AttributeError: 'NoneType' object has no attribute 'set_text'
```

I can confirm that this is only after the fix for #13. Then from here if I hit OK, I see the error below. Due to this I cannot edit an existing server. 

```
Traceback (most recent call last):
  File "gnome_connection_manager.py", line 2529, in on_okbutton1_clicked
    term = self.txtTerm.get_text()        
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by msmigiel** [comment]
Sorry, this is my mistake. I only took `gnome_connection_manager.py`.
