### ISSUE TITLE
Crashed in Kubuntu 20.04

### ISSUE THREAD

**Issue by schmel** [kuthulux/gnome-connection-manager#46]
I use 1.2.1 release. 

```
AB350M-DS3H-V2:~$ python3 /usr/share/gnome-connection-manager/gnome_connection_manager.py
Traceback (most recent call last):
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 173, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 176, in <module>
    print >> sys.stderr, "python3-gi required"
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?

```

**Comment by kuthulux** [comment]
Hi
you have to install python3-gi gor it to work.

but it shouldn't crash like that, i will fix  that "print" (it's python2 syntax) to give a proper error message in the console.

**Comment by schmel** [comment]
doesn't work out

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.36.0-1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
```

```
AB350M-DS3H-V2:~$ dpkg -l | grep python3-gi
ii  python3-gi                                    3.36.0-1                                    amd64        Python 3 bindings for gobject-introspection libraries
```

**Comment by kuthulux** [comment]
look like your machine doesn't have vte installed

try installing this package:
gir1.2-vte-2.91

it should install these automatically:
libvte-2.91-0
libvte-2.91-common

**Comment by schmel** [comment]
Thanks, it work.

**Comment by kuthulux** [comment]
great, 
I will include that package as a dependency in the deb and the readme so others using KDE wont have that problem.
