### ISSUE TITLE
unable to launch version 1.2.1 on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by veremchook** [kuthulux/gnome-connection-manager#65]
It installed fine:

```
sudo dpkg -i gnome-connection-manager_1.2.1_all.deb 
Selecting previously unselected package gnome-connection-manager.
(Reading database ... 191950 files and directories currently installed.)
Preparing to unpack gnome-connection-manager_1.2.1_all.deb ...
Unpacking gnome-connection-manager (1.2.1) ...
Setting up gnome-connection-manager (1.2.1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
```
but fails to launch:

```
/usr/share/gnome-connection-manager$ ./gnome_connection_manager.py 
Invalid entry in configuration file: No option 'cycle-tabs' in section: 'options'
./gnome_connection_manager.py:1541: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  menu.set_image(Gtk.Image.new_from_icon_name(Gtk.STOCK_DIRECTORY, Gtk.IconSize.MENU))
./gnome_connection_manager.py:1566: DeprecationWarning: Gtk.StyleContext.get_background_color is deprecated
  rgba = self.treeServers.get_style_context().get_background_color(Gtk.StateFlags.NORMAL)
Traceback (most recent call last):
  File "./gnome_connection_manager.py", line 3390, in <module>
    main()
  File "./gnome_connection_manager.py", line 3386, in main
    w_main = Wmain()
  File "./gnome_connection_manager.py", line 460, in __init__
    provider.load_from_path(BASE_PATH + "/style.css")
gi.repository.GLib.Error: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /usr/share/gnome-connection-manager/style.css: No such file or directory (2)
```
Is it complaining about legacy config from my previous Ubuntu 18.04 installation?
I built a massive structure under the previous version and I'm really keen to re-use it rather than manually recreate from scratch.
Any quick hack or other advice?

**Comment by veremchook** [comment]
That was it, working now.
Thank you for a quick reply and this nice tool.
