### ISSUE TITLE
crash on ubuntu 22.04

### ISSUE THREAD

**Issue by sergico** [kuthulux/gnome-connection-manager#81]
Hi,

just installed version `1.2.1` on `Ubuntu 22.04` and got a crash
Here the traceback

```
borghese@NR054-UB:~$ /usr/share/gnome-connection-manager/gnome_connection_manager.py 
Invalid entry in configuration file: No section: 'options'
/usr/share/gnome-connection-manager/gnome_connection_manager.py:1566: DeprecationWarning: Gtk.StyleContext.get_background_color is deprecated
  rgba = self.treeServers.get_style_context().get_background_color(Gtk.StateFlags.NORMAL)
/usr/share/gnome-connection-manager/gnome_connection_manager.py:868: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  menuItem.set_image(Gtk.Image.new_from_icon_name(Gtk.STOCK_COPY, Gtk.IconSize.MENU))
Traceback (most recent call last):
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 3390, in <module>
    main()
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 3386, in main
    w_main = Wmain()
  File "/usr/share/gnome-connection-manager/gnome_connection_manager.py", line 460, in __init__
    provider.load_from_path(BASE_PATH + "/style.css")
gi.repository.GLib.GError: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /usr/share/gnome-connection-manager/style.css: No such file or directory (2)
```
version `1.2.0` on the very same system works fine
python version is `3.10.4`
Tried to delete the config folder `.gcm` and start the software again, but got the same error

Please let me know if I can send you any more useful details to debug the issue

**Comment by jimklimov** [comment]
I think the culprit is

    provider.load_from_path(BASE_PATH + "/style.css") gi.repository.GLib.GError: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /usr/share/gnome-connection-manager/style.css: No such file or directory (2)

which is a known issue in last-made package (see other github issues). Download the fike from sources here into that directory, and all should become ok.
